# Generated by Django 5.1.3 on 2024-11-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ourapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('regular', 'Regular User')], default='regular', max_length=10),
        ),
    ]
